export const MERCENARIES = [
  {
    id: 'goblin_berserker',
    name: 'Brakka Sang Berserker',
    title: 'Goblin Bruiser & Bodyguard',
    avatar: '👹',
    role: 'Tank / Melee',
    color: '#eab308',
    radius: 15,
    maxHp: 200,
    attack: 22,
    defense: 16,
    speed: 3.0,
    attackRange: 45,
    attackCooldown: 1.2,
    skillName: 'Earthquake Slam',
    skillDesc: 'Menghantam tanah membuat musuh tertegun (Stun).',
    skillCooldown: 6.0,
    costGold: 100,
    unlocked: true,
    desc: 'Goblin setia bersenjatakan gada besi raksasa yang siap pasang badan melindungi tuannya.'
  },
  {
    id: 'skeleton_warlock',
    name: 'Kaelen Sang Necro',
    title: 'Penyihir Tulang Es',
    avatar: '💀',
    role: 'Ranged Caster',
    color: '#38bdf8',
    radius: 14,
    maxHp: 130,
    attack: 34,
    defense: 8,
    speed: 3.2,
    attackRange: 200,
    attackCooldown: 1.5,
    projectileSpeed: 6.5,
    skillName: 'Freezing Bolt',
    skillDesc: 'Melontarkan panah es yang memperlambat musuh.',
    skillCooldown: 7.0,
    costGold: 250,
    unlocked: false,
    desc: 'Kerangka purba yang dibangkitkan dari kubur dungeon, ahli menembakkan proyektil es dari kejauhan.'
  },
  {
    id: 'shadow_hellhound',
    name: 'Fenris Hound',
    title: 'Serigala Api Neraka',
    avatar: '🐺',
    role: 'Fast Assassin',
    color: '#ef4444',
    radius: 16,
    maxHp: 160,
    attack: 28,
    defense: 12,
    speed: 4.2,
    attackRange: 40,
    attackCooldown: 0.9,
    skillName: 'Flame Bite',
    skillDesc: 'Gigitan api yang membakar musuh secara berkala.',
    skillCooldown: 5.0,
    costGold: 500,
    unlocked: false,
    desc: 'Binatang buas penjaga gerbang neraka dengan cakar api dan pergerakan sangat gesit.'
  }
];
