export const MONSTER_TYPES = {
  slime: {
    id: 'slime',
    name: 'Toxic Slime',
    color: '#22c55e',
    glowColor: 'rgba(34, 197, 94, 0.4)',
    radius: 14,
    maxHp: 55,
    attack: 8,
    defense: 2,
    speed: 1.4,
    xpReward: 15,
    goldReward: [5, 12],
    behavior: 'chase',
    attackCooldown: 1.5,
    attackRange: 26
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin Scout',
    color: '#eab308',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    radius: 15,
    maxHp: 85,
    attack: 14,
    defense: 4,
    speed: 2.1,
    xpReward: 25,
    goldReward: [12, 25],
    behavior: 'chase',
    attackCooldown: 1.2,
    attackRange: 32
  },
  skeleton_archer: {
    id: 'skeleton_archer',
    name: 'Skeleton Archer',
    color: '#cbd5e1',
    glowColor: 'rgba(203, 213, 225, 0.4)',
    radius: 16,
    maxHp: 70,
    attack: 16,
    defense: 3,
    speed: 1.2,
    xpReward: 30,
    goldReward: [15, 30],
    behavior: 'ranged_kite',
    attackCooldown: 2.0,
    attackRange: 160,
    projectileSpeed: 4.5
  },
  orc_berserker: {
    id: 'orc_berserker',
    name: 'Orc Berserker',
    color: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.5)',
    radius: 22,
    maxHp: 200,
    attack: 26,
    defense: 8,
    speed: 1.8,
    xpReward: 60,
    goldReward: [35, 65],
    behavior: 'chase',
    attackCooldown: 1.6,
    attackRange: 38
  },
  boss_gargoyle: {
    id: 'boss_gargoyle',
    name: 'Gargoyle Overlord [BOSS]',
    isBoss: true,
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.7)',
    radius: 34,
    maxHp: 750,
    attack: 38,
    defense: 16,
    speed: 1.5,
    xpReward: 300,
    goldReward: [150, 300],
    gemReward: [5, 10],
    behavior: 'boss_complex',
    attackCooldown: 2.2,
    attackRange: 50,
    phases: [
      { hpThreshold: 1.0, attackMode: 'cleave_and_summon' },
      { hpThreshold: 0.5, attackMode: 'enraged_earthquake' }
    ]
  },
  boss_necromancer: {
    id: 'boss_necromancer',
    name: 'Lich King Malakor [BOSS]',
    isBoss: true,
    color: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.8)',
    radius: 36,
    maxHp: 1200,
    attack: 52,
    defense: 22,
    speed: 1.3,
    xpReward: 650,
    goldReward: [350, 600],
    gemReward: [12, 25],
    behavior: 'boss_complex',
    attackCooldown: 1.8,
    attackRange: 180,
    phases: [
      { hpThreshold: 1.0, attackMode: 'dark_orbs' },
      { hpThreshold: 0.4, attackMode: 'chaos_nova_barrage' }
    ]
  }
};
